### PR TITLE
Add tip about debug overhead

### PR DESCRIPTION
**Pull request by dev590t**

### CODE REVIEW

**Review by rocky — APPROVED** [review]
LGTM - there are small changes I'll make down the line, but for now this is good. 

I will be out of town for a little more than a week.

**Comment by dev590t** [comment]
yeah^^

**Comment by rocky** [comment]
@dev590t Due to work in using this debugger for use in the open source Mathematica project, [Mathics3](https://mathics3.org), I have been working on this project recently, and have fixed several problems in the slowness around using "finish", "next", and "continue". 

I have also gone over the document to [explain the situation better](https://python3-trepan.readthedocs.io/en/latest/commands/running.html).  There is still some slowness compared to `pdb`. I am not completely sure what exactly is wrong or different. But the code is faster (and has fewer bugs in hangs).

**Comment by dev590t** [comment]
nice!

**Comment by rocky** [comment]
> nice!

Nice, but it would be even better to figure out where the additional overhead is still coming from in trepan3k that isn't in `pdb`.  Some callbacks to the debugger occur that it feels like should not be happening.

What's weird is that this code has way more information about the program at its disposal that `pdb` doesn't have. How to make even better _use_ of it is still a mystery.

**Pull request merged**
